<footer> 
            <p>Heres an email link to our company if you have any further questions: <a href="mailto:info@ctrlaltdefend.com"> Email:📧</a></p>
            <p> Link to our Jira account: <a href="https://scanjira.atlassian.net/jira/software/projects/SCRUM/summary">Jira</a> </p>
            <p> Link to our Github: <a href="https://github.com/khanhchi0148/project-1" target="_blank">Github</a> </p>
</footer>