<img id="image" src="images/cs.png" alt="image"> <!--Adding a image for stylizing-->
        <section id="general" class="section"> <!--This part is individual to the others above so i give it an id for further designs-->
            <h3>General</h3>
            <!--In this section i use both ordered and unordered lists to state the general requirements for applicants-->
            <h4>Knowledge & attributes</h4>
            <ol>
                <li>Programming languages: <strong>Python, Java, C, C++, SQL, PHP, HTML</strong> </li>
                <li>Years of experience required: <strong>1-3 years</strong></li>
            </ol>
            <h4>Overall skills</h4>
            <ul id="overall"> <!--Sets an id for further stylization-->
                <li>Programming skills</li>
                <li>Adaptability to new technologies</li>
                <li>Ability to work under pressure</li>
                <li>Creativity</li>
                <li>Communication and teamwork skills</li>
            </ul>
        </section>